# Generated by Django 2.2.10 on 2021-07-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
